name: ml
channels:
  - pytorch
  - https://conda.anaconda.org/NLeSC
  - defaults
dependencies:
  - appnope=0.1.0=py36hf537a9a_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - ca-certificates=2019.5.15=0
  - certifi=2019.6.16=py36_0
  - cffi=1.12.3=py36hb5b8e2f_0
  - cycler=0.10.0=py36hfc81398_0
  - decorator=4.4.0=py36_1
  - freetype=2.9.1=hb4e5f40_0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.1=py36h39e3cac_0
  - ipython=7.5.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - jedi=0.13.3=py36_0
  - joblib=0.13.2=py36_0
  - jpeg=9b=he5867d9_2
  - jupyter_client=5.2.4=py36_0
  - jupyter_core=4.4.0=py36_0
  - kiwisolver=1.1.0=py36h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - libtiff=4.0.10=hcb84e12_2
  - llvm-openmp=4.0.1=hcfea43d_1
  - matplotlib=3.1.0=py36h54f8f79_0
  - mkl=2019.4=233
  - mkl-service=2.0.2=py36h1de35cc_0
  - mkl_fft=1.0.12=py36h5e564d8_0
  - mkl_random=1.0.2=py36h27c97d8_0
  - ncurses=6.1=h0a44026_1
  - ninja=1.9.0=py36h04f5b5a_0
  - numpy=1.16.4=py36hacdab7b_0
  - numpy-base=1.16.4=py36h6575580_0
  - olefile=0.46=py36_0
  - openssl=1.1.1c=h1de35cc_1
  - parso=0.4.0=py_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=6.0.0=py36hb68e598_0
  - pip=19.1.1=py36_0
  - prompt_toolkit=2.0.9=py36_0
  - ptyprocess=0.6.0=py36_0
  - pycparser=2.19=py36_0
  - pygments=2.4.2=py_0
  - pyparsing=2.4.0=py_0
  - python=3.6.8=haf84260_0
  - python-dateutil=2.8.0=py36_0
  - pytorch=1.1.0=py3.6_0
  - pytz=2019.1=py_0
  - pyzmq=18.0.0=py36h0a44026_0
  - readline=7.0=h1de35cc_5
  - scikit-learn=0.21.2=py36h27c97d8_0
  - scipy=1.2.1=py36h1410ff5_0
  - setuptools=41.0.1=py36_0
  - six=1.12.0=py36_0
  - sqlite=3.28.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - torchvision=0.3.0=py36_cuNone_1
  - tornado=6.0.2=py36h1de35cc_0
  - traitlets=4.3.2=py36h65bd3ce_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - wheel=0.33.4=py36_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.3.1=h0a44026_3
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - pip:
    - appdirs==1.4.3
    - attrs==19.1.0
    - black==19.3b0
    - click==7.0
    - jsonpatch==1.23
    - jsonpointer==2.0
    - jsonschema==3.0.1
    - pyhf==0.1.0
    - pyrsistent==0.15.1
    - toml==0.10.0
    - tqdm==4.31.1
prefix: /Users/johannbrehmer/anaconda3/envs/ml

