name: ml
channels:
  - pytorch
  - https://conda.anaconda.org/NLeSC
  - defaults
dependencies:
  - matplotlib>=3.0.0
  - numpy>=1.16.0
  - pip
  - python>=3.6.0
  - pytorch>=1.3.0
  - scikit-learn>=0.21.0
  - scipy>=1.2.0
  - torchvision>=0.4.0
  - palettable
  - pip:
    - black
    - geomloss
prefix: /Users/johannbrehmer/anaconda3/envs/ml
